### ISSUE TITLE
Can it be compiled on CentOS 7?

### ISSUE THREAD

**Issue by DRVTiny** [j8r/cride#1]
I was trying to install dependencies for cride, but got:
```
Fetching https://github.com/j8r/clicr.git
Fetching https://github.com/j8r/crystal-autobind.git
Fetching https://github.com/ysbaddaden/clang.cr.git
Using clicr (0.3.5)
Installing autobind (0.4.1 at 0.4.2)
Postinstall shards build
Failed shards build:
Fetching https://github.com/ysbaddaden/clang.cr.git
Installing clang (0.2.0 at 349a9185bc9a1756dd4c682c000764ec31a3b5da)
Building: autobind
Error target autobind failed to compile:
/usr/bin/ld: cannot find -lclang (this usually means you need to install the development package for libclang)
collect2: error: ld returned 1 exit status
Error: execution of command failed with code: 1: `cc "${@}" -o '/home/a.konovalov/Apps/Crystal/editors/cride/lib/autobind/bin/autobind'  -rdynamic  -lpcre -lgc -lpthread /usr/share/crystal/src/ext/libcrystal.a -levent -lrt `/usr/local/bin/llvm-config --ldflags 2> /dev/null` -lclang -ldl -L/usr/lib -L/usr/local/lib`
```
There is no libclang package in CentOS 7, but there is clang-devel. I've installed that package, but problem still stays here. I suppose that installation of clang and llvm from scratch may help me, but i dont want to break my distributive's package system (last hope for epel-devel repository). 
Is there is some way to avoid dependency on autobind in cride?

Thanks!

**Comment by j8r** [comment]
I've added docs about building a statically-linked `cride` binary using Docker and Alpine.
Hope it helps :smile:

**Comment by j8r** [comment]
To further explain, we need bindings to get the screen size with the `Winsize` struct, which also requires the `TIOCGWINSZ` constant.
We could pre-generate the bindings for each system/architecture to avoid to have `libclang` installed, but since we are there we have shorter to directly generate the binaries.
