### ISSUE TITLE
Index Out of Bounds Error

### ISSUE THREAD

**Issue by rinkimekari** [j8r/cride#2]
When using cride on any file, new or not, using a tab and then any key, I get an index out of bounds error. 
The error:
```
An error as occured. Please create an issue at https://github.com/j8r/cride with the steps to how reproduce this bug.

cursor_y:  1, cursor_x: 64
page_y:    1, page_x: 1
file_rows: 2, row_size: 4
Message: "Index out of bounds"
Backtrace:
/usr/lib/crystal/string.cr:1669:5 in 'insert'
/home/micah/programs/crystal/cride/src/file_handler/add.cr:6:16 in 'char'
/home/micah/programs/crystal/cride/src/editor/add.cr:8:5 in 'add_char'
/home/micah/programs/crystal/cride/src/terminal.cr:58:13 in 'main_loop'
/home/micah/programs/crystal/cride/src/terminal.cr:15:5 in 'initialize'
/home/micah/programs/crystal/cride/src/terminal.cr:8:3 in 'new:file_handler:color'
/home/micah/programs/crystal/cride/src/cli.cr:24:5 in 'new_terminal'
/home/micah/programs/crystal/cride/src/cli.cr:44:11 in 'open_files'
/home/micah/programs/crystal/cride/src/cli.cr:17:7 in 'run'
/home/micah/programs/crystal/cride/src/cli.cr:6:3 in 'run'
/home/micah/programs/crystal/cride/src/cli.cr:53:1 in '__crystal_main'
/usr/lib/crystal/crystal/main.cr:110:5 in 'main_user_code'
/usr/lib/crystal/crystal/main.cr:96:7 in 'main'
/usr/lib/crystal/crystal/main.cr:119:3 in 'main'
__libc_start_main
_start
???
```
This happened when I created a new file and tried to indent using a tab, but my cursor disappeared and pressing enter caused the program to crash. I tried this several more times, each time breaking the program.

I also tried this with a file that was written to already, and indenting worked fine for the first "tab" keypress, but then any key after that breaks the program except for the escape key, which obviously just exits the program.

Please let me know if you have any other questions, and I look forward to seeing what this project can become!

**Comment by j8r** [comment]
Tab is a weird character indeed. It is a single character taking 4 spaces. Thanks, I can reproduce the issue.

**Comment by j8r** [comment]
Fixed now, thanks!

**Comment by rinkimekari** [comment]
:+1:
